// picorv32_core.sv
// PicoRV32 CPU + internal RAM, exposes IO bus for non-RAM transactions.
//
// Memory map:
//   0x00000000 - 0x000xFFFF  RAM (internal, generated by programator.py)
//   else                      → IO bus (exposed externally)
//
// IO bus uses native PicoRV32 interface (mem_valid/addr/wdata/wstrb/ready/rdata)
// External wrapper (e.g. picorv32_apb_soc) connects bus bridge here.

`timescale 1ns/1ps

module picorv32_core #(
    parameter BARREL_SHIFTER = 0,
    parameter ENABLE_MUL     = 0,
    parameter ENABLE_DIV     = 0,
    parameter ENABLE_IRQ     = 0,
    parameter RAM_ADDR_BITS  = 11
) (
    input  logic        clk,
    input  logic        resetn,

    // IO bus — non-RAM transactions exit here
    output logic        io_valid,
    output logic [31:0] io_addr,
    output logic [31:0] io_wdata,
    output logic [ 3:0] io_wstrb,
    input  logic [31:0] io_rdata,
    input  logic        io_ready
);
    // ── PicoRV32 native interface ────────────────────────────────────────────
    logic        mem_valid;
    logic [31:0] mem_addr;
    logic [31:0] mem_wdata;
    logic [ 3:0] mem_wstrb;
    logic        mem_ready;
    logic [31:0] mem_rdata;

    picorv32 #(
        .ENABLE_MUL    (ENABLE_MUL),
        .ENABLE_DIV    (ENABLE_DIV),
        .ENABLE_IRQ    (ENABLE_IRQ),
        .BARREL_SHIFTER(BARREL_SHIFTER)
    ) u_cpu (
        .clk      (clk),
        .resetn   (resetn),
        .mem_valid(mem_valid),
        .mem_ready(mem_ready),
        .mem_addr (mem_addr),
        .mem_wdata(mem_wdata),
        .mem_wstrb(mem_wstrb),
        .mem_rdata(mem_rdata)
    );

    // ── Address decode ───────────────────────────────────────────────────────
    logic ram_sel;
    logic io_sel;
    assign ram_sel = mem_valid && (mem_addr[31:RAM_ADDR_BITS+2] == 0);
    assign io_sel  = mem_valid && !ram_sel;

    // ── RAM (generated by programator.py) ────────────────────────────────────
    logic        ram_ready;
    logic [31:0] ram_rdata;

    ram u_ram (
        .clk      (clk),
        .mem_valid(ram_sel),
        .mem_addr (mem_addr[RAM_ADDR_BITS+1:2]),
        .mem_wdata(mem_wdata),
        .mem_wstrb(mem_wstrb),
        .mem_rdata(ram_rdata),
        .mem_ready(ram_ready)
    );

    // ── IO bus exposed externally ────────────────────────────────────────────
    assign io_valid = io_sel;
    assign io_addr  = mem_addr;
    assign io_wdata = mem_wdata;
    assign io_wstrb = mem_wstrb;

    // ── Memory mux back to CPU ───────────────────────────────────────────────
    assign mem_ready = ram_sel ? ram_ready : (io_sel ? io_ready : 1'b0);
    assign mem_rdata = ram_sel ? ram_rdata : io_rdata;

endmodule
