current_dir := ${CURDIR}
ANVIL_HOME ?= $(HOME)/opt/anvil
TARGET := nexys_a7_50t
TOP := top
SOURCES := ${current_dir}/*.v
XDC := ${current_dir}/Nexys-A7-50T-Master.xdc

include ${current_dir}/common/common.mk
